coverage:
  precision: 2
  round: down
  range: 50..100

  status:
    project:
      default:
        target: 1%
        threshold: 0.5%
        informational: true
    patch:
      default:
        target: 1%
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true